#!/bin/bash
# The logic to stop your application should be put in this script.

SOLR_VERSION=5.0.0
SOLR_PATH=${OPENSHIFT_REPO_DIR}solr-${SOLR_VERSION}/
export PATH=${SOLR_PATH}bin/:$PATH

echo -e "Stop solr-${SOLR_VERSION}"
solr stop 
